services:
  db:
    container_name: dundertasks-postgres
    image: postgres
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres
  redis:
    image: "redis:latest"
    container_name: redis_queue
    ports:
      - "6379:6379"
